group:
  - files:
    - source: ../ISSUE_TEMPLATE/
      dest: .github/ISSUE_TEMPLATE/
      exclude: repos/*
    repos: |
      pezaio/gateway
      pezaio/api-docs
      pezaio/identity

  - files:
    - source: ../ISSUE_TEMPLATE/config.yml
      dest: .github/ISSUE_TEMPLATE/config.yml
    - source: ../ISSUE_TEMPLATE/repos/pezaio/
      dest: .github/ISSUE_TEMPLATE/
    repos: |
      pezaio/pezaio
