# These settings are synced to GitHub by https://github.com/github/safe-settings
repository:
  name: openarch-api
  #force_create: true
  #template_repo: template_repo
  # has_issues: false

milestones:
  - title: Whatever2
    description: Whatever2 description
    state: open
  - title: Whatever3
    description: Whatever3 description
    state: open
