# These settings are synced to GitHub by https://github.com/github/safe-settings
repository:
  name: openarch-api
  #force_create: true
  #template_repo: template_repo
  # has_issues: false

milestones:
  - title: Whatever
    description: Whatever3 new description
    state: open
