---
name: Sync issue templates

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
      runs-on: ubuntu-latest
      steps:
      
        - name: Checkout
          uses: actions/checkout@v2

        - name: Run GitHub file Sync
          uses: Redocly/repo-file-sync-action@main
          with:
            GH_PAT: ${{ secrets.GH_PAT }}
            CONFIG_PATH: .github/sync-issue-templates.yml
            COMMIT_PREFIX: 'chore: '
            COMMIT_BODY: 'sync issue templates'
            PR_LABELS: |
              file-sync
              automerge
